# Generated by Django 2.1.7 on 2019-03-30 19:09

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20190330_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('user_image', models.ImageField(height_field='height', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.image_upload_path, width_field='width')),
                ('city', models.CharField(max_length=50)),
                ('bank_account_no', models.CharField(max_length=100)),
                ('user_id_number', models.CharField(max_length=100)),
                ('id_photo_upper', models.ImageField(height_field='height', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.file_upload_path, verbose_name='Id Card Upper Image', width_field='width')),
                ('id_photo_bottom', models.ImageField(height_field='height', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.file_upload_path, verbose_name='Id Card Bottom Image', width_field='width')),
                ('driving_license_number', models.CharField(max_length=100)),
                ('driving_license_photo_upper', models.ImageField(height_field='height', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.file_upload_path, verbose_name='Driving License Upper Image', width_field='width')),
                ('driving_license_photo_bottom', models.ImageField(height_field='height', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.file_upload_path, verbose_name='Driving License Bottom Image', width_field='width')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user.Bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
