# Generated by Django 2.1.7 on 2019-03-30 19:14

import django.core.files.storage
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='driving_license_photo_bottom',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.file_upload_path, verbose_name='Driving License Bottom Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='driving_license_photo_upper',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.file_upload_path, verbose_name='Driving License Upper Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_photo_bottom',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.file_upload_path, verbose_name='Id Card Bottom Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_photo_upper',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage(location='/home/hasan/Documents/django_project/repository/comingoo/server/mediabrowser_files'), upload_to=user.models.file_upload_path, verbose_name='Id Card Upper Image'),
        ),
    ]
